## Service definition ##
application:
  schemaVersion: 0.0.1
  name: VotingApp
  services:
    - name: VotingWeb
      description: VotingWeb front-end service
      osType: Windows
      codePackages:
        - name: VotingWeb
          image: votingweb:dev
          endpoints:
            - name: VotingWebListener
              port: 8080
          environmentVariables:
            - name: ASPNETCORE_URLS
              value: http://+:8080
#            - name: ApplicationInsights:InstrumentationKey
#              value: "<Place AppInsights key here, or reference it via a secret>"
#            Use the below value for Win10 debugging
            - name: Voting_BackendHostName
              value: votingdata.votingapp
#            Use the below value for publishing to Azure Mesh
#            - name: Voting_BackendHostName
#              value: votingdata
            - name: Voting_BackendHostPort
              value: 8288
          resources:
            requests:
              cpu: 0.5
              memoryInGB: 1
      replicaCount: 1
      networkRefs:
        - name: VotingAppNetwork