## Service definition ##
application:
  schemaVersion: 0.0.1
  name: VisualObjects
  services:
    - name: worker
      description: worker description.
      osType: Windows
      codePackages:
        - name: worker
          image: worker:dev
          endpoints:
            - name: workerListener
              port: 20009
          resources:
            requests:
              cpu: 0.5
              memoryInGB: 1
      replicaCount: 1
      networkRefs:
        - name: VisualObjectsNetwork