## Service definition ##
application:
  schemaVersion: 0.0.1
  name: VisualObjects
  services:
    - name: web
      description: web description.
      osType: Windows
      codePackages:
        - name: web
          image: web:dev
          endpoints:
            - name: webListener
              port: 20005
          environmentVariables:
            - name: ASPNETCORE_URLS
              value: http://+:80
#            - name: ApplicationInsights:InstrumentationKey
#              value: "<Place AppInsights key here, or reference it via a secret>"
          resources:
            requests:
              cpu: 0.5
              memoryInGB: 1
      replicaCount: 1
      networkRefs:
        - name: VisualObjectsNetwork